# 每天00:00执行

name: Start

on:
   push:
   gollum:
   schedule:
       - cron: '00 16 * * *'

jobs:
  AutoSign:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        mvn compile exec:java -Dexec.mainClass="stand.ronghui.Main" -Dexec.args="${USERNAME} ${PASSWORD}"
